test0c: test0.c
	gcc -o test0_c test0.c; ./test0_c
test0py: test0.py
	python test0.py
test0java: test0.java
	javac test0.java; java test0
test0pl: test0.pl
	perl test0.pl
test0cpp: test0.cpp
	g++ -o test0_cpp test0.cpp; ./test0_cpp
test0php: test0.php
	php test0.php
test0rb: test0.rb
	ruby test0.rb
test0r: test0.r
	Rscript test0.r
test0sh: test0.sh
	sh test0.sh

clean:
	rm -rf test0_c test0 test1 test2 test3 test4 test0_cpp
